# Generated by Django 3.1.6 on 2021-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
